name: CI

on:
  push:
    branches: ['**']

jobs:
  ci:
  runs-on: ubuntu-latest

  stategy:
    matrix:
      node-version: [12.x]

  steps:
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn
    - run: yarn lint
    - run: yarn build
